###
GET http://localhost:3333

###
POST http://localhost:3333/jogadores
Content-Type: application/json

{
  "NOME": "Yuri Alberto",
  "description": "Atacante do Corinthians",
  "NUMCAMISA": 9
}

###
GET http://localhost:3333/jogadores
###

POST http://localhost:3333/jogadores
Content-Type: application/json

{
  "NOME": "Yuri Alberto",
  "description": "Atacante do Corinthians",
  "NUMCAMISA": 9
}

###
GET http://localhost:3333/jogadores