GET http://localhost:3333

###

GET http://localhost:3333/videos

###

GET http://localhost:3333/videos/1

###

POST http://localhost:3333/videos
Content-Type: application/json

{
  "titulo": "Memphis Depay",
  "descricao": "Melhores momentos",
  "url": "https://youtube.com/video3"
}