GET http://localhost:3333

###

GET http://localhost:3333/corinthians

###

GET http://localhost:3333/jogadores

###

POST http://localhost:3333/jogadores
Content-Type: application/json

{
  "id": 3,
  "nome": "Memphis Depay",
  "numero": 10,
  "posicao": "Atacante",
  "idade": 30
}